links:
  wikidata_rest_endpoint: "https://www.wikidata.org/w/rest.php/wikibase/v1"
  wikidata_sparql_endpoint: "https://query.wikidata.org/sparql"
  dbpedia_sparql_endpoint: "https://dbpedia.org/sparql"
  dbpedia_resource_base: "http://dbpedia.org/resource"
search:
  language: "en"
  keywords:
    en:
      - "software"
      - "program"
      - "application"
      - "framework"
      - "library"
      - "platform"
      - "tool"
      - "utility"
      - "package"
      - "module"
      - "system"
      - "engine"
      - "runtime"
      - "virtualization"
      - "container"
      - "operating system"
      - "os"
      - "kernel"
      - "driver"
      - "middleware"
      - "api"
      - "sdk"
      - "ide"
      - "compiler"
      - "interpreter"
      - "database"
      - "server"
      - "client"
    ru:
      - "программное обеспечение"
      - "программа"
      - "приложение"
      - "фреймворк"
      - "библиотека"
      - "платформа"
      - "инструмент"
      - "утилита"
      - "пакет"
      - "модуль"
      - "система"
      - "движок"
      - "среда выполнения"
      - "виртуализация"
      - "контейнер"
      - "операционная система"
      - "ос"
      - "ядро"
      - "драйвер"
      - "промежуточное по"
      - "интерфейс"
      - "компилятор"
      - "интерпретатор"
      - "база данных"
      - "сервер"
      - "клиент"
